spring:
  datasource:  # 配置mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/tutor?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: relife.l
  main:
    allow-bean-definition-overriding: true

server:
  port: 8080  # 默认端口
  
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml 
  type-aliases-package: com.gyl.tutor.dao